name = "StanDistributions"
uuid = "c79ef891-62a4-4b64-9d5a-fce85bcd6f75"
authors = ["Seth Axen <seth@sethaxen.com> and contributors"]
version = "0.1.0"

[deps]
BridgeStan = "c88b6f0a-829e-4b0b-94b7-f06ab5908f5a"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[extensions]
StanDistributionsBijectorsExt = "Bijectors"
StanDistributionsChainRulesCoreExt = "ChainRulesCore"
StanDistributionsForwardDiffExt = "ForwardDiff"

[compat]
Bijectors = "0.13"
BridgeStan = "1, 2"
ChainRulesCore = "1"
Distributions = "0.23, 0.24, 0.25"
DocStringExtensions = "0.9"
ForwardDiff = "0.10"
Requires = "1"
julia = "1.6"

[extras]
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
